### ISSUE TITLE
能否解决一下dio依赖版本过低的问题？

### ISSUE THREAD

**Issue by JerrySir** [Sky24n/flutter_wanandroid#100]
`Because every version of base_library from git depends on dio 1.0.13 and client depends on dio ^3.0.3, base_library from git is forbidden.

So, because client depends on base_library from git, version solving failed.
pub get failed (1)`

package get报错，我们依赖的dio版本是dio: ^3.0.7

请教，如何解决？我们只想用里面的SplashPage功能

**Comment by JerrySir** [comment]
@Sky24n

**Comment by Sky24n** [comment]
base_library个人使用，暂不会升级！
你可以直接使用Flutter常用工具类库flustars: ^0.2.6+1
