### ISSUE TITLE
编译时报错

### ISSUE THREAD

**Issue by alexpreston** [Sky24n/flutter_wanandroid#103]
Compiler message:
../../flutterSDK/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../flutterSDK/flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.
Error launching application on iPhone 8.

**Comment by Sky24n** [comment]
cached_network_image: 2.0.0

**Comment by nvkou** [comment]
不止这个错误。这个项目停止维护一段时间了。和最新的sdk有兼容性问题。而且有几个包是并不是包管理器管理的。要把那些复制过来的本地包删掉。

**Comment by Sky24n** [comment]
Flutter (Channel stable, v1.12.13+hotfix.5)没有任何问题；ps：android.
