### ISSUE TITLE
Error: Type 'DateFormat' not found.

### ISSUE THREAD

**Issue by TenXu** [Sky24n/flutter_wanandroid#104]
作者你好
本人初学者，老早之前就下载过这个，但之前是代码版本过低运行不了，但这次是找不到类运行不了，好无语，求大佬赐教
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/12495409/82801443-e82dc300-9eaf-11ea-80e9-ae9d8d552bab.png">

**Comment by Sky24n** [comment]
这种简单的问题，应该自己动手解决。

**Comment by TenXu** [comment]
@Sky24n 好吧，就是自己解决不了才来问一下，我再看看怎么弄，感谢

**Comment by kening6666** [comment]
同问，这是少了哪个依赖

**Comment by Sky24n** [comment]
Duplicate of #105

**Comment by Sky24n** [comment]
fix
