### ISSUE TITLE
【IOS】ios运行后无法找到install_apk_plugin 插件，请教一下是为何

### ISSUE THREAD

**Issue by yyfd2013zy** [Sky24n/flutter_wanandroid#107]
console如下
-> Fetching podspec for `install_apk_plugin` from `.symlinks/plugins/install_apk_plugin/ios`
    [!] No podspec found for `install_apk_plugin` in `.symlinks/plugins/install_apk_plugin/ios`

**Comment by nbhhcty** [comment]
我也遇到这个问题，😅

**Comment by yyfd2013zy** [comment]
是否是install_apk_plugin这个插件的ios native代码兼容问题，还需要请作者看一下了

**Comment by Sky24n** [comment]
fix

**Comment by PhantomRay** [comment]
这个问题解决了吗？Mac下会有这个问题。

**Comment by yyfd2013zy** [comment]
作者说fix了，我还没试。我是把作者的base_library,由网络依赖改为了本地依赖，剔除了升级功能的依赖，解决了这个问题

**Comment by PhantomRay** [comment]
哦，没看懂。谢谢。
