### ISSUE TITLE
有错误

### ISSUE THREAD

**Issue by yangsl2014** [Sky24n/flutter_wanandroid#11]
SuspensionUtil  ISuspensionBean找不到呢

**Comment by Sky24n** [comment]
把flukit的缓存删了，重新flutter packages get
.pub-cache/git/flukit-.....

**Comment by yangsl2014** [comment]
照做了，依然不行

**Comment by Sky24n** [comment]
先pull一下最新代码，然后看看azlistview有没有

**Comment by Sky24n** [comment]
@yangsl2014 pull下最新代码，把flukit缓存删了，把项目里的pubspec.lock文件删了，重新flutter packages get

**Comment by yangsl2014** [comment]
好了，谢谢
