### ISSUE TITLE
升级了最新得flutter sdk  有api不能用了

### ISSUE THREAD

**Issue by sinduanan** [Sky24n/flutter_wanandroid#115]
其他api都已经修改，但是有一处api不知道该怎么改，网上搜索无果，求教：

在lib/blocs/bloc_provider.dart中：

`static T of<T extends BlocBase>(BuildContext context) {
    final type = _typeOf<BlocProvider<T>>();
    BlocProvider<T> provider = context.ancestorWidgetOfExactType(type);
    return provider.bloc;
  }`

context.ancestorWidgetOfExactType(type);这里不知道该怎么修改。。。求教

sdk  Channel stable, 2.0.2

**Comment by Sky24n** [comment]
fix,更新下代码

**Comment by sinduanan** [comment]
👍
