### ISSUE TITLE
image_picker 问题

### ISSUE THREAD

**Issue by laowangDemon** [Sky24n/flutter_wanandroid#117]
Android拍照的图片上传异常，iOS截图上传异常
可能是因为UploadFileInfo被去掉了,需要换成MultipartFile.
但是base_library依赖dio1.0.13，MultipartFile需要3.0.8
现在是base_library也没法升级，dio也没法升级

**Comment by Sky24n** [comment]
你fork份自己改不就行了

**Comment by laowangDemon** [comment]
> 你fork份自己改不就行了

😌，会的话就不来问大佬了

**Comment by laowangDemon** [comment]
![image](https://user-images.githubusercontent.com/35515568/114824875-0e29c200-9df8-11eb-8e61-ce8e795c6fee.png)

**Comment by laowangDemon** [comment]
搞定了，用这个
[github.com/Willdas/FlutterRepos.git](url)
