### ISSUE TITLE
OPPO 上貌似有兼容性问题？

### ISSUE THREAD

**Issue by wangyongf** [Sky24n/flutter_wanandroid#12]
我的手机是 OPPO R15，有两个问题：

1. 打开应用时，直接提示不支持全屏显示，应该是未适配全面屏？
2. 打开任意一个文章详情页，都黑屏了，标题部分显示正常，标题下面的内容部分黑了

我是从 README 扫码下载的。

![image](https://user-images.githubusercontent.com/12151492/51787082-3e99cd00-21a8-11e9-857f-b9d06a69d252.png)

![image](https://user-images.githubusercontent.com/12151492/51787083-4194bd80-21a8-11e9-9ae6-2360fecd6142.png)

**Comment by Sky24n** [comment]
1，你可以点击下面的【点击全屏显示】就可以全面屏了。
2，oppo R15确实有这个问题，开启全面屏后就无法显示网页了，非全面屏的时候我这边能打开网页。我用的是google官方的0.2.0webview插件。
