### ISSUE TITLE
flutter packages get失败

### ISSUE THREAD

**Issue by syydbc** [Sky24n/flutter_wanandroid#13]
webview_flutter:
    git:
      url: git://github.com/Sky24n/plugins.git
      ref: newDev
      path: packages/webview_flutter/

fatal: ambiguous argument 'newDev': unknown revision or path not in the working tree.

没有找到你的newDev呢

**Comment by Sky24n** [comment]
git 引包在win上面问题有点多，我这边mac是没有问题的，windows也半天没有啦下来

**Comment by Sky24n** [comment]
实在不行你把包clone到本地，改成本地引用吧
