### ISSUE TITLE
打开文章详情页bug

### ISSUE THREAD

**Issue by tigerzy** [Sky24n/flutter_wanandroid#14]
使用oppo r11st测试有下述问题：竖屏时打开文章详情页，页面空白，横屏时则可正常显示。在文章详情页横竖屏切换经常会闪退。报了如下错误：
E/AndroidRuntime(11882): java.lang.NullPointerException: Attempt to invoke virtual method 'void android.view.Display.getSize(android.graphics.Point)' on a null object reference
E/AndroidRuntime(11882):        at org.chromium.ui.display.DisplayAndroid.updateFromDisplay(DisplayAndroid.java:133)
E/AndroidRuntime(11882):        at org.chromium.ui.display.DisplayAndroidManager$DisplayListenerBackendImpl.onDisplayChanged(DisplayAndroidManager.java:169)
E/AndroidRuntime(11882):        at android.hardware.display.DisplayManagerGlobal$DisplayListenerDelegate.handleMessage(DisplayManagerGlobal.java:462)
E/AndroidRuntime(11882):        at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime(11882):        at android.os.Looper.loop(Looper.java:185)
E/AndroidRuntime(11882):        at android.app.ActivityThread.main(ActivityThread.java:6615)
E/AndroidRuntime(11882):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(11882):        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:916)
E/AndroidRuntime(11882):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:806)

**Comment by Sky24n** [comment]
你看下官方[webview_flutter](https://github.com/flutter/plugins/tree/master/packages/webview_flutter)最新版是不是正常的？我用的0.2.0版

**Comment by yk3372** [comment]
请问你是怎么解决这个问题的呀？
