### ISSUE TITLE
ios启动白屏

### ISSUE THREAD

**Issue by GuixiangCao** [Sky24n/flutter_wanandroid#18]
ios启动的时候白屏...

**Comment by Sky24n** [comment]
我这边改了效果不好，所以没有改。
解决方法：
iOS
要将图片添加到启动屏幕（splash screen）的中心，请导航至.../ios/Runner。在Assets.xcassets/LaunchImage.imageset， 拖入图片，并命名为images LaunchImage.png、LaunchImage@2x.png、LaunchImage@3x.png。

**Comment by GuixiangCao** [comment]
好多 多谢了
