### ISSUE TITLE
更新：wanandroid 切换至 https

### ISSUE THREAD

**Issue by hongyangAndroid** [Sky24n/flutter_wanandroid#22]
为了满足小程序等开发需求，wanandroid 域名切换为https啦，需要尽快更新下 baseurl，目前可能部分http接口会异常，有问题及时反馈我，谢谢！

**Comment by Sky24n** [comment]
已知晓，感谢～

> 为了满足小程序等开发需求，wanandroid 域名切换为https啦，需要尽快更新下 baseurl，目前可能部分http接口会异常，有问题及时反馈我，谢谢！
