### ISSUE TITLE
关于网络请求的疑问

### ISSUE THREAD

**Issue by itlws** [Sky24n/flutter_wanandroid#26]
作者你好，我现在刚开始学习flutter，有很多东西还不了解，现在遇到一个问题，想请教下作者，就是关于网络请求，当页面关闭的时候，需不需要手动关闭网络请求，页面发起网络请求，跟页面的声明周期有没有关联，关闭页面后，如果网络请求没完成，会不会造成内存泄漏？还请作者不吝赐教！

**Comment by Sky24n** [comment]
这个我暂时没有去测试过，你可以先测试下有没有内存泄漏的情况

**Comment by YeFei572** [comment]
之前我碰到过类似问题，在java写的安卓项目里面，当一个请求结果没返回来用户就把请求终止了， 结果后台就报错，这个错误会累积，多了就直接内存溢出了。然后我在web端也模拟一下，也会出现这种问题。 看日志类似于 Broken pipe一样的异常
