### ISSUE TITLE
老铁啥时候重构好啊

### ISSUE THREAD

**Issue by qq326646683** [Sky24n/flutter_wanandroid#3]

**Comment by qq326646683** [comment]
请问main.dart里setLocalizedValues、CustomLocalizations哪里来的啊

**Comment by ztiandan** [comment]
下载了最新代码flutter packages get时，总提示以下错误是咋回事呢？

[flutter_wanandroid-master] flutter packages get
Running "flutter packages get" in flutter_wanandroid-master...     
Could not find a file named "pubspec.yaml" in git://github.com/Sky24n/flutter_webview_plugin.git 5391447fae6209bb21a89e6a5a6583cac1af9b4b.

pub get failed (1)
exit code 1

**Comment by ztiandan** [comment]
@Sky24n 好像还是不行

Dannys-MacBook-Pro:flutter_wanandroid-master danny$ export PUB_HOSTED_URL=https://pub.flutter-io.cn
Dannys-MacBook-Pro:flutter_wanandroid-master danny$ export FLUTTER_STORAGE_BASE_URL=https://storage.flutter-io.cn
Dannys-MacBook-Pro:flutter_wanandroid-master danny$ flutter packages get
Running "flutter packages get" in flutter_wanandroid-master...
Could not find a file named "pubspec.yaml" in git://github.com/Sky24n/flutter_webview_plugin.git 5391447fae6209bb21a89e6a5a6583cac1af9b4b.

pub get failed (1)

**Comment by Sky24n** [comment]
@ztiandan 加我QQ  863764940

**Comment by qq326646683** [comment]
老铁，没有重构的代码可以放出来不，我看homepage，eventspage都是空的，一脸懵逼
