### ISSUE TITLE
收藏项目无效，在收藏列表里面没有，而且进入收藏列表一直转菊花，即使断网也没有提示网络情况

### ISSUE THREAD

**Issue by GuixiangCao** [Sky24n/flutter_wanandroid#39]

**Comment by Sky24n** [comment]
因为没有登录注册，所以收藏功能是还没有开发的。
另外，最新版0.2.0，是有网络状态的界面的。
收藏界面如图
![page_empty](https://user-images.githubusercontent.com/15412262/56114280-fc0bb380-5f92-11e9-93db-5abced5af2b8.png)

**Comment by GuixiangCao** [comment]
多谢

**Comment by GuixiangCao** [comment]
多谢回复，git上代码跑起来好像没有网络状态。

**Comment by jp1017** [comment]
> git上代码跑起来好像没有网络状态。

确实没有 @Sky24n

**Comment by Sky24n** [comment]
git上版本0.1.5

**Comment by jp1017** [comment]
> 仓库版本0.1.5

最新的还是不行，，，
