### ISSUE TITLE
编译不通过

### ISSUE THREAD

**Issue by fdtl01** [Sky24n/flutter_wanandroid#40]
![image](https://user-images.githubusercontent.com/36351484/56140715-00a18d80-5fce-11e9-8a2f-80d74c3a04e8.png)

**Comment by Sky24n** [comment]
33楼有解决方法


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by fdtl01** [comment]
> 33楼有解决方法
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

感谢，方法如下
修改 pubspec.yaml 里的pull_to_refresh即可，去掉^ 符号，问题是因为pull_to_refresh升级导致的
