### ISSUE TITLE
ios 模拟器 run 报错

### ISSUE THREAD

**Issue by lingstart** [Sky24n/flutter_wanandroid#43]
Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used instead.
  running Flutter tool: /Users/chenlin/app/flutter
  previous reference  : /Users/chenlin/flutter
This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).

Launching lib/main.dart on 测试机 in debug mode...
Removing obsolete reference to flutter_assets from Runner.app
Signing iOS app for device deployment using developer identity: "iPhone Developer: Ji Hai Wu (622CA8F9X9)"
Xcode build done.                                           12.9s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **
Xcode's output:
↳
    === BUILD TARGET path_provider OF PROJECT Pods WITH CONFIGURATION Debug ===
    /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: warning: 'sqlite3_wal_checkpoint_v2' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'SQLite3' imported from /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabase.m:8:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/sqlite3.h:8244:16: note: 'sqlite3_wal_checkpoint_v2' has been explicitly marked partial here
    SQLITE_API int sqlite3_wal_checkpoint_v2(
                   ^
    /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabase.m:1486:15: note: enclose 'sqlite3_wal_checkpoint_v2' in an @available check to silence this warning
        int err = sqlite3_wal_checkpoint_v2(_db, dbName, checkpointMode, logFrameCount, checkpointCount);
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
    1 warning generated.
    /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: warning: 'dispatch_queue_set_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1352:1: note: 'dispatch_queue_set_specific' has been explicitly marked partial here
    dispatch_queue_set_specific(dispatch_queue_t queue, const void *key,
    ^
    /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:101:9: note: enclose 'dispatch_queue_set_specific' in an @available check to silence this warning
            dispatch_queue_set_specific(_queue, kDispatchQueueSpecificKey, (__bridge void *)self, NULL);
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: warning: 'dispatch_get_specific' is only available on iOS 5.0 or newer [-Wunguarded-availability]
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    In module 'Foundation' imported from /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.h:9:
    In module 'CoreFoundation' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
    In module 'Dispatch' imported from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFStream.h:20:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/usr/include/dispatch/queue.h:1408:1: note: 'dispatch_get_specific' has been explicitly marked partial here
    dispatch_get_specific(const void *key);
    ^
    /Users/chenlin/Downloads/flutter_wanandroid-master/ios/Pods/FMDB/src/fmdb/FMDatabaseQueue.m:184:54: note: enclose 'dispatch_get_specific' in an @available check to silence this warning
        FMDatabaseQueue *currentSyncQueue = (__bridge id)dispatch_get_specific(kDispatchQueueSpecificKey);
                                                         ^~~~~~~~~~~~~~~~~~~~~
    2 warnings generated.
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:33:52: warning: 'WKWebsiteDataTypeCookies' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      NSSet *websiteDataTypes = [NSSet setWithArray:@[ WKWebsiteDataTypeCookies ]];
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:47:28: note: 'WKWebsiteDataTypeCookies' has been explicitly marked partial here
    WK_EXTERN NSString * const WKWebsiteDataTypeCookies API_AVAILABLE(macosx(10.11), ios(9.0));
                               ^
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:33:52: note: enclose 'WKWebsiteDataTypeCookies' in an @available check to silence this warning
      NSSet *websiteDataTypes = [NSSet setWithArray:@[ WKWebsiteDataTypeCookies ]];
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:3: warning: 'WKWebsiteDataStore' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
      ^~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:41:12: note: 'WKWebsiteDataStore' has been explicitly marked partial here
    @interface WKWebsiteDataStore : NSObject <NSSecureCoding>
               ^
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:3: note: enclose 'WKWebsiteDataStore' in an @available check to silence this warning
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
      ^~~~~~~~~~~~~~~~~~
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:36: warning: 'WKWebsiteDataStore' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
                                       ^~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataStore.h:41:12: note: 'WKWebsiteDataStore' has been explicitly marked partial here
    @interface WKWebsiteDataStore : NSObject <NSSecureCoding>
               ^
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:34:36: note: enclose 'WKWebsiteDataStore' in an @available check to silence this warning
      WKWebsiteDataStore *dataStore = [WKWebsiteDataStore defaultDataStore];
                                       ^~~~~~~~~~~~~~~~~~
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:36:35: warning: 'WKWebsiteDataRecord' is only available on iOS 9.0 or newer [-Wunguarded-availability]
      void (^deleteAndNotify)(NSArray<WKWebsiteDataRecord *> *) =
                                      ^~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:66:12: note: 'WKWebsiteDataRecord' has been explicitly marked partial here
    @interface WKWebsiteDataRecord : NSObject
               ^
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:36:35: note: enclose 'WKWebsiteDataRecord' in an @available check to silence this warning
      void (^deleteAndNotify)(NSArray<WKWebsiteDataRecord *> *) =
                                      ^~~~~~~~~~~~~~~~~~~
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:37:17: warning: 'WKWebsiteDataRecord' is only available on iOS 9.0 or newer [-Wunguarded-availability]
          ^(NSArray<WKWebsiteDataRecord *> *cookies) {
                    ^~~~~~~~~~~~~~~~~~~
    In module 'WebKit' imported from /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.h:2:
    /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS12.1.sdk/System/Library/Frameworks/WebKit.framework/Headers/WKWebsiteDataRecord.h:66:12: note: 'WKWebsiteDataRecord' has been explicitly marked partial here
    @interface WKWebsiteDataRecord : NSObject
               ^
    /Users/chenlin/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.5+3/ios/Classes/FLTCookieManager.m:37:17: note: enclose 'WKWebsiteDataRecord' in an @available check to silence this warning
          ^(NSArray<WKWebsiteDataRecord *> *cookies) {
                    ^~~~~~~~~~~~~~~~~~~
    5 warnings generated.
    === BUILD TARGET Runner OF PROJECT Runner WITH CONFIGURATION Debug ===
    Warning! The 'flutter' tool you are currently running is from a different Flutter repository than the one last used by this package. The repository from which the 'flutter' tool is currently executing will be used instead.
      running Flutter tool: /Users/chenlin/app/flutter
      previous reference  : /Users/chenlin/flutter
    This can happen when you have multiple copies of flutter installed. Please check your system path to verify that you are running the expected version (run 'flutter --version' to see which flutter is on your path).
    Compiler message:
    file:///Users/chenlin/flutter/packages/flutter/lib/src/scheduler/binding.dart:245:69: Error: The getter 'initialLifecycleState' isn't defined for the class 'Window'.
     - 'Window' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'initialLifecycleState'.
        if (_lifecycleState == null && _parseAppLifecycleMessage(window.initialLifecycleState) != null) {
                                                                        ^^^^^^^^^^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/scheduler/binding.dart:246:38: Error: The getter 'initialLifecycleState' isn't defined for the class 'Window'.
     - 'Window' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'initialLifecycleState'.
          _handleLifecycleMessage(window.initialLifecycleState);
                                         ^^^^^^^^^^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/painting/text_style.dart:905:7: Error: No named parameter with the name 'decorationThickness'.
          decorationThickness: decorationThickness,
          ^^^^^^^^^^^^^^^^^^^
    org-dartlang-sdk:///flutter/lib/ui/text.dart:377:3: Context: Found this candidate, but the arguments don't match.
      TextStyle({
      ^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:103:62: Error: Getter not found: 'PointerSignalKind'.
          if (datum.signalKind == null || datum.signalKind == ui.PointerSignalKind.none) {
                                                                 ^^^^^^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:420:19: Error: Getter not found: 'PointerSignalKind'.
              case ui.PointerSignalKind.scroll:
                      ^^^^^^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:487:19: Error: Getter not found: 'PointerSignalKind'.
              case ui.PointerSignalKind.none:
                      ^^^^^^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:490:19: Error: Getter not found: 'PointerSignalKind'.
              case ui.PointerSignalKind.unknown:
                      ^^^^^^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:103:17: Error: The getter 'signalKind' isn't defined for the class 'PointerData'.
     - 'PointerData' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'signalKind'.
          if (datum.signalKind == null || datum.signalKind == ui.PointerSignalKind.none) {
                    ^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:103:45: Error: The getter 'signalKind' isn't defined for the class 'PointerData'.
     - 'PointerData' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'signalKind'.
          if (datum.signalKind == null || datum.signalKind == ui.PointerSignalKind.none) {
                                                ^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:419:23: Error: The getter 'signalKind' isn't defined for the class 'PointerData'.
     - 'PointerData' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'signalKind'.
            switch (datum.signalKind) {
                          ^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:478:30: Error: The getter 'scrollDeltaX' isn't defined for the class 'PointerData'.
     - 'PointerData' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'scrollDeltaX'.
                    Offset(datum.scrollDeltaX, datum.scrollDeltaY) / devicePixelRatio;
                                 ^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/gestures/converter.dart:478:50: Error: The getter 'scrollDeltaY' isn't defined for the class 'PointerData'.
     - 'PointerData' is from 'dart:ui'.
    Try correcting the name to the name of an existing getter, or defining a getter or field named 'scrollDeltaY'.
                    Offset(datum.scrollDeltaX, datum.scrollDeltaY) / devicePixelRatio;
                                                     ^^^^^^^^^^^^
    file:///Users/chenlin/flutter/packages/flutter/lib/src/semantics/semantics.dart:1952:7: Error: No named parameter with the name 'platformViewId'.
          platformViewId: data.platformViewId != null ? data.platformViewId : -1,
          ^^^^^^^^^^^^^^
    Compiler failed on /Users/chenlin/Downloads/flutter_wanandroid-master/lib/main.dart
    Failed to package /Users/chenlin/Downloads/flutter_wanandroid-master.
Could not build the precompiled application for the device.

Error launching application on 测试机.
Exited (sigterm)

**Comment by Sky24n** [comment]
我这边是正常的，ios不太懂，，，

**Comment by lengqingfeng** [comment]
iOS not work
