### ISSUE TITLE
大佬能更新下pull_to_refresh插件的问题吗

### ISSUE THREAD

**Issue by az18780007577** [Sky24n/flutter_wanandroid#44]
报了很多错 refreshStatus状态问题,大佬麻烦优化一下呗

**Comment by rellyCheng** [comment]
同上

**Comment by rellyCheng** [comment]
pubspec.yaml 文件       45行 pull_to_refresh: ^1.1.6 改 pull_to_refresh: 1.1.6   就好了

**Comment by az18780007577** [comment]
大佬你注册登录的代码开源了吗?down最新的代码没有注册登录呀




------------------ 原始邮件 ------------------
发件人: "relly"<notifications@github.com>;
发送时间: 2019年4月23日(星期二) 上午9:01
收件人: "Sky24n/flutter_wanandroid"<flutter_wanandroid@noreply.github.com>;
抄送: "245369209"<245369209@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [Sky24n/flutter_wanandroid] 大佬能更新下pull_to_refresh插件的问题吗 (#44)




pubspec.yaml 文件       45行 pull_to_refresh: ^1.1.6 改 pull_to_refresh: 1.1.6   就好了
