### ISSUE TITLE
Error: The argument type 'int' can't be assigned to the parameter type 'Refr

### ISSUE THREAD

**Issue by wsb0617** [Sky24n/flutter_wanandroid#45]
<img width="1240" alt="图片" src="https://user-images.githubusercontent.com/5467640/56493879-1ad5f100-6523-11e9-9ecc-fe843df8ab90.png">

**Comment by LLemonGreen** [comment]
pubspec.yaml

**Comment by LLemonGreen** [comment]
pubspec.yaml
里面pull_to_refresh: ^1.1.6
改为pull_to_refresh: 1.1.6
flutter clean

flutter packages get

**Comment by MRZHL** [comment]
ok thank you

**Comment by JokerLoLgrey** [comment]
> flutter clean

兄弟还是不行啊

**Comment by hanqingkai** [comment]
找了好久才找到这个答案
