### ISSUE TITLE
更新app

### ISSUE THREAD

**Issue by rcj60560** [Sky24n/flutter_wanandroid#46]
你好，请问下能方便做一个更新模块吗，好多东西不太明白，点击，获取版本号并且比较，更新。
这个用安卓好做，flutter没搞过，一头雾水 @Sky24n @gopalvirat

**Comment by hehuapei** [comment]
同希望作者能分享下应用内升级代码!
自己仿照着做了个,不知道做法对不对 [安卓app应用内升级demo](https://github.com/hehuapei/flutter-demo/tree/master/app_update_demo)
