### ISSUE TITLE
想看下闪屏视频是如何实现的，现在代码的运行效果没有适配闪屏，能告诉用的什么插件，或者更新下代码吗，感谢

### ISSUE THREAD

**Issue by Mrjen** [Sky24n/flutter_wanandroid#50]

**Comment by Sky24n** [comment]
用dio下载，videoplayer播放就行了


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by Mrjen** [comment]
> 用dio下载，videoplayer播放就行了
> 
> :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

在闪屏的时候下载视频会来的及吗，如果网速不是很快的话是不是要黑屏一段时间，还是这个可以边下边播

**Comment by Sky24n** [comment]
在App或者主页里面下载就可以了。
