### ISSUE TITLE
您好，5.8号升级的登录注册应用内升级的版本可以开源一下么？

### ISSUE THREAD

**Issue by leeyao1991** [Sky24n/flutter_wanandroid#51]

**Comment by magicvz** [comment]
同问。。。

**Comment by gzfarmer** [comment]
同问。。。

**Comment by doramart** [comment]
确实没看到代码

**Comment by wowngasb** [comment]
嗯嗯，希望作者有时间能跟新一下，十分感谢

**Comment by magicvz** [comment]
如果 我没有猜错，你们是想要登录注册的widget吧。呵呵。。
如果 是的话，你在个人信息里面找到“收藏”，里面就会有。
如果 不是的话，当我没有说。

**Comment by hlj2722** [comment]
抽屉页面 没有 **趋势** 这一模块，目测代码确实没有更新完全

**Comment by hehuapei** [comment]
同希望作者能分享下应用内升级代码!
自己仿照着做了个,不知道做法对不对 [安卓app应用内升级demo](https://github.com/hehuapei/flutter-demo/tree/master/app_update_demo)
