### ISSUE TITLE
代码好像没有更新完全

### ISSUE THREAD

**Issue by HeartDawnWY** [Sky24n/flutter_wanandroid#52]
比如 main_block 
        288行 RefreshStatus.noMore 这个枚举中没有 noMore对象
        291行 RefreshStatus.failed

com_list_page.dart 类中
         16行  _controller.sendBack 没有这个sendBack方法

**Comment by magicvz** [comment]
pubspec.yaml
里面pull_to_refresh: ^1.1.6
改为pull_to_refresh: 1.1.6
flutter clean

flutter packages get

====刚运行起来，呵呵。

**Comment by huang12zheng** [comment]
thank you very much.
@magicvz

**Comment by YikuCCCCCC** [comment]
> pubspec.yaml
> 里面pull_to_refresh: ^1.1.6
> 改为pull_to_refresh: 1.1.6
> flutter clean
> 
> flutter packages get
> 
> ====刚运行起来，呵呵。

老哥稳
