### ISSUE TITLE
Android Studio 运行报错

### ISSUE THREAD

**Issue by houqinzhe** [Sky24n/flutter_wanandroid#54]
Compiler message:
lib/ui/pages/home_page.dart:103:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/pages/repos_page.dart:18:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/pages/events_page.dart:18:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/pages/rec_hot_page.dart:39:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/blocs/main_bloc.dart:237:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:241:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/main_bloc.dart:258:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:262:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/main_bloc.dart:288:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:291:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/main_bloc.dart:316:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:319:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/com_list_bloc.dart:82:52: Error: Getter not found: 'noMore'.
          ObjectUtil.isEmpty(list) ? RefreshStatus.noMore : RefreshStatus.idle,
                                                   ^^^^^^
lib/blocs/com_list_bloc.dart:86:68: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _comListEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                   ^
lib/blocs/com_list_bloc.dart:99:52: Error: Getter not found: 'noMore'.
          ObjectUtil.isEmpty(list) ? RefreshStatus.noMore : RefreshStatus.idle,
                                                   ^^^^^^
lib/blocs/com_list_bloc.dart:103:68: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _comListEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                   ^
lib/blocs/com_list_bloc.dart:119:52: Error: Getter not found: 'noMore'.
          ObjectUtil.isEmpty(list) ? RefreshStatus.noMore : RefreshStatus.idle,
                                                   ^^^^^^
lib/blocs/com_list_bloc.dart:123:68: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _comListEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                   ^
lib/ui/widgets/com_list_page.dart:16:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///Users/sean/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.6/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/widgets/refresh_scaffold.dart:85:17: Error: 'RefreshIndicator' is imported from both 'package:flutter/src/material/refresh_indicator.dart' and 'package:pull_to_refresh/src/internals/indicator_wrap.dart'.
            new RefreshIndicator(
                ^^^^^^^^^^^^^^^^
Compiler failed on /Users/sean/Downloads/flutter_wanandroid-master/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by GlobalQiu** [comment]
pubspec.yaml 中的pull_to_refresh: ^1.1.6 改成 pull_to_refresh: 1.1.6

**Comment by houqinzhe** [comment]
完美解决这个问题，刚研究flutter，对error信息捕获不敏感

**Comment by Mr-Cai** [comment]
很多方法名都更改了，也不告诉人一声
