### ISSUE TITLE
有人遇到这个问题吗，帮忙解决一下

### ISSUE THREAD

**Issue by 1135291424** [Sky24n/flutter_wanandroid#55]
![image](https://user-images.githubusercontent.com/19277817/58394135-53ae3c00-8074-11e9-830b-3d12b54c1fdd.png)

**Comment by HeiSiBaby** [comment]
同求

**Comment by Sky24n** [comment]
切到beta开发分支

**Comment by lebow01** [comment]
> 切到beta开发分支

上面就一个master分支呢

**Comment by Sky24n** [comment]
Duplicate of #[10](https://github.com/Sky24n/flustars/issues/10)
