### ISSUE TITLE
更新 AS之后报的错，求大佬给个解决方法

### ISSUE THREAD

**Issue by houqinzhe** [Sky24n/flutter_wanandroid#56]
Compiler message:
file:///Users/sean/.pub-cache/hosted/pub.dartlang.org/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///Users/sean/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
file:///Users/sean/.pub-cache/hosted/pub.dartlang.org/flustars-0.2.5/lib/src/widget_util.dart:88:8: Error: No named parameter with the name 'onError'.
    }, onError: (dynamic exception, StackTrace stackTrace) {
       ^^^^^^^
file:///Users/sean/.pub-cache/hosted/pub.dartlang.org/flustars-0.2.5/lib/src/widget_util.dart:115:8: Error: No named parameter with the name 'onError'.
    }, onError: (dynamic exception, StackTrace stackTrace) {
       ^^^^^^^
Compiler failed on /Users/sean/Downloads/flutter_wanandroid-master/lib/main.dart

FAILURE: Build failed with an exception.

* Where:
Script '/Users/sean/flutter/packages/flutter_tools/gradle/flutter.gradle' line: 647

* What went wrong:
Execution failed for task ':app:compileflutterBuildDebugandroid-arm'.
> Process 'command '/Users/sean/flutter/bin/flutter'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by Sky24n** [comment]
切到beta分支


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by houqinzhe** [comment]
只能看到一个 master 开发分支

**Comment by Sky24n** [comment]
flutter beta分支

**Comment by houqinzhe** [comment]
ooo
