### ISSUE TITLE
你好，项目导入时Widget里的refresh_scaffold.dart有错

### ISSUE THREAD

**Issue by yemeihanxing** [Sky24n/flutter_wanandroid#57]
提示'RefreshIndicator' is imported from both 'package:flutter/src/material/refresh_indicator.dart' and 'package:pull_to_refresh/src/internals/indicator_wrap.dart' 这个应该要如何解决

**Comment by yemeihanxing** [comment]
#

- 

1. 

- [ ] ` new RefreshIndicator(
                child: new SmartRefresher(
                    controller: widget.controller,
                    enablePullDown: false,
                    enablePullUp: widget.enablePullUp,
                    enableOverScroll: false,
                    onRefresh: widget.onLoadMore,
                    child: widget.child ??
                        new ListView.builder(
                          itemCount: widget.itemCount,
                          itemBuilder: widget.itemBuilder,
                        )),
                onRefresh: widget.onRefresh),`

**Comment by Sky24n** [comment]
pubspec.yaml 中的pull_to_refresh: ^1.1.6 改成 pull_to_refresh: 1.1.6
