### ISSUE TITLE
运行项目后执行,flutter packages get还是有报错

### ISSUE THREAD

**Issue by dengwuqiang19899** [Sky24n/flutter_wanandroid#59]
报错内容:
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:82)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:86)
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:99)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:103)
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:119)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\com_list_bloc.dart:123)
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\main_bloc.dart:237)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\main_bloc.dart:241)
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\main_bloc.dart:258)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\main_bloc.dart:262)
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\main_bloc.dart:288)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\main_bloc.dart:291)
error: The getter 'noMore' isn't defined for the class 'RefreshStatus'. (undefined_getter at [flutter_wanandroid] lib\blocs\main_bloc.dart:316)
error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'. (argument_type_not_assignable at [flutter_wanandroid] lib\blocs\main_bloc.dart:319)
error: The method 'sendBack' isn't defined for the class 'RefreshController'. (undefined_method at [flutter_wanandroid] lib\ui\pages\events_page.dart:18)
error: The method 'sendBack' isn't defined for the class 'RefreshController'. (undefined_method at [flutter_wanandroid] lib\ui\pages\home_page.dart:103)
error: The method 'sendBack' isn't defined for the class 'RefreshController'. (undefined_method at [flutter_wanandroid] lib\ui\pages\rec_hot_page.dart:39)
error: The method 'sendBack' isn't defined for the class 'RefreshController'. (undefined_method at [flutter_wanandroid] lib\ui\pages\repos_page.dart:18)
error: The method 'sendBack' isn't defined for the class 'RefreshController'. (undefined_method at [flutter_wanandroid] lib\ui\widgets\com_list_page.dart:16)
error: The name 'RefreshIndicator' is defined in the libraries 'package:flutter/src/material/refresh_indicator.dart' and 'package:pull_to_refresh/src/internals/indicator_wrap.dart'. (ambiguous_import at [flutter_wanandroid] lib\ui\widgets\refresh_scaffold.dart:85)
error: The constructor returns type 'dynamic' that isn't of expected type 'Widget'. (strong_mode_invalid_cast_new_expr at [flutter_wanandroid] lib\ui\widgets\refresh_scaffold.dart:85)
error: The named parameter 'enableOverScroll' isn't defined. (undefined_named_parameter at [flutter_wanandroid] lib\ui\widgets\refresh_scaffold.dart:90)

如果运行的话:
Compiler message:
lib/ui/pages/home_page.dart:103:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/pages/repos_page.dart:18:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/pages/events_page.dart:18:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/pages/rec_hot_page.dart:39:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/blocs/main_bloc.dart:237:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:241:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/main_bloc.dart:258:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:262:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/main_bloc.dart:288:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:291:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/main_bloc.dart:316:31: Error: Getter not found: 'noMore'.
              ? RefreshStatus.noMore
                              ^^^^^^
lib/blocs/main_bloc.dart:319:65: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _homeEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                ^
lib/blocs/com_list_bloc.dart:82:52: Error: Getter not found: 'noMore'.
          ObjectUtil.isEmpty(list) ? RefreshStatus.noMore : RefreshStatus.idle,
                                                   ^^^^^^
lib/blocs/com_list_bloc.dart:86:68: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _comListEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                   ^
lib/blocs/com_list_bloc.dart:99:52: Error: Getter not found: 'noMore'.
          ObjectUtil.isEmpty(list) ? RefreshStatus.noMore : RefreshStatus.idle,
                                                   ^^^^^^
lib/blocs/com_list_bloc.dart:103:68: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _comListEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                   ^
lib/blocs/com_list_bloc.dart:119:52: Error: Getter not found: 'noMore'.
          ObjectUtil.isEmpty(list) ? RefreshStatus.noMore : RefreshStatus.idle,
                                                   ^^^^^^
lib/blocs/com_list_bloc.dart:123:68: Error: The argument type 'RefreshStatus' can't be assigned to the parameter type 'int'.
 - 'RefreshStatus' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try changing the type of the parameter, or casting the argument to 'int'.
      _comListEventSink.add(new StatusEvent(labelId, RefreshStatus.failed));
                                                                   ^
lib/ui/widgets/com_list_page.dart:16:21: Error: The method 'sendBack' isn't defined for the class 'RefreshController'.
 - 'RefreshController' is from 'package:pull_to_refresh/src/smart_refresher.dart' ('file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart').
Try correcting the name to the name of an existing method, or defining a method named 'sendBack'.
        _controller.sendBack(false, event.status);
                    ^^^^^^^^
lib/ui/widgets/refresh_scaffold.dart:90:21: Error: No named parameter with the name 'enableOverScroll'.
                    enableOverScroll: false,
                    ^^^^^^^^^^^^^^^^
file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/pull_to_refresh-1.3.9/lib/src/smart_refresher.dart:54:3: Context: Found this candidate, but the arguments don't match.
  SmartRefresher(
  ^
lib/ui/widgets/refresh_scaffold.dart:85:17: Error: 'RefreshIndicator' is imported from both 'package:flutter/src/material/refresh_indicator.dart' and 'package:pull_to_refresh/src/internals/indicator_wrap.dart'.
            new RefreshIndicator(
                ^^^^^^^^^^^^^^^^
file:///D:/flutter_sdk/flutter/.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-0.7.0/lib/src/cached_network_image_provider.dart:46:31: Error: The argument type 'Null Function(StringBuffer)' can't be assigned to the parameter type 'Iterable<DiagnosticsNode> Function()'.
 - 'StringBuffer' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'DiagnosticsNode' is from 'package:flutter/src/foundation/diagnostics.dart' ('file:///D:/flutter_sdk/flutter/packages/flutter/lib/src/foundation/diagnostics.dart').
Try changing the type of the parameter, or casting the argument to 'Iterable<DiagnosticsNode> Function()'.
        informationCollector: (StringBuffer information) {
                              ^
Compiler failed on E:\flutter\git\flutter_wanandroid\lib/main.dart

请问大神 ,要怎么解决?

**Comment by yt19860606** [comment]
请问你解决了么？我也是同样的问题，我的是墙后外网环境，应该不存在问题啊
![屏幕快照 2019-05-29 下午1 35 35](https://user-images.githubusercontent.com/7424719/58531968-b17a8980-8216-11e9-8afe-1b3397679dc7.png)

**Comment by yt19860606** [comment]
解决啦

pubspec.yaml 中的pull_to_refresh: ^1.1.6 改成 pull_to_refresh: 1.1.6

**Comment by jishaofeng89** [comment]
这两个有什么区别哟

**Comment by Sky24n** [comment]
后面那个使用指定版本

**Comment by jishaofeng89** [comment]
请问地图部分在哪里，我下载了apk没有看到地图的实现，我想参考下

**Comment by DemoJiang** [comment]
> 请问地图部分在哪里，我下载了apk没有看到地图的实现，我想参考下
项目中有地图吗？你说的不会是项目启动的视频吧？那是启动页
