### ISSUE TITLE
Error: Method not found: 'ImageStreamListener'.

### ISSUE THREAD

**Issue by lebow01** [Sky24n/flutter_wanandroid#61]
![image](https://user-images.githubusercontent.com/23068980/58759536-633ef080-855e-11e9-9fa5-6351c7638827.png)

**Comment by lebow01** [comment]
![image](https://user-images.githubusercontent.com/23068980/58759650-004e5900-8560-11e9-95d7-c31c3f4c769f.png)

**Comment by lebow01** [comment]
.addListener(new ImageStreamListener(
          (ImageInfo info, bool _) {
            completer.complete(Rect.fromLTWH(0, 0, info.image.width.toDouble(),
                info.image.height.toDouble()));
          },
          onError: (dynamic exception, StackTrace stackTrace) {
            completer.completeError(exception, stackTrace);
          },
        ));


我把这个删除能运行了，不知道这里是干吗用的，，，作者出来说明下 这里到底能不能删除

**Comment by Sky24n** [comment]
Duplicate of #[10](https://github.com/Sky24n/flustars/issues/10)

**Comment by lebow01** [comment]
> Duplicate of [10](https://github.com/Sky24n/flustars/issues/10)   三克油

**Comment by ahSHH** [comment]
这个问题怎么解决呢

**Comment by Sky24n** [comment]
flutter beta分支v1.5.4-hotfix.2，请用0.2.5版本。
flutter beta分支v1.6.3，请用0.2.5+1版本。

**Comment by xuyifeiOnly** [comment]
这个0.2.5版本，指的是哪个呀，在哪修改的？

**Comment by zhuxcye** [comment]
[image: image.png]

xuyifeiOnly <notifications@github.com> 于2019年6月16日周日 下午2:32写道：

**Comment by zhuxcye** [comment]
flutter  channel beta 

![image](https://user-images.githubusercontent.com/30371524/59574126-acf41300-90e8-11e9-9131-38415b054fb2.png)

**Comment by Sky24n** [comment]
本项目基于Flutter (Channel beta, v1.6.3, locale zh-Hans-CN)开发！
请自行升级Flutter版本！
flutter upgrade
