### ISSUE TITLE
ImageStreamListener的报错没有解决啊

### ISSUE THREAD

**Issue by Jasonli1558** [Sky24n/flutter_wanandroid#63]
![image](https://user-images.githubusercontent.com/14233470/59178733-7111f880-8b92-11e9-9bbb-ffb08213b59a.png)

**Comment by Sky24n** [comment]
flutter beta分支v1.5.4-hotfix.2，请用0.2.5版本。
flutter beta分支v1.6.3，请用0.2.5+1版本。

**Comment by dhlsoft** [comment]
base_library from git depends on flustars >=0.2.6 <1.0.0

**Comment by mko2008mko** [comment]
![image](https://user-images.githubusercontent.com/5045998/59672507-32171f00-91f2-11e9-8356-bafffd5b04ff.png)
还是这问题

**Comment by mko2008mko** [comment]
![image](https://user-images.githubusercontent.com/5045998/59672554-49560c80-91f2-11e9-8ccd-55f1f900575b.png)

**Comment by Sky24n** [comment]
Flutter (Channel beta, v1.6.3, locale zh-Hans-CN)
dart-sdk 最低 v2.1.0
以上是最低支持版本，如不是，请自行升级！
flutter upgrade

**Comment by nnianhou-** [comment]
<img width="1135" alt="屏幕快照 2019-06-19 16 28 55" src="https://user-images.githubusercontent.com/10951126/59749555-cdba9500-92af-11e9-8a75-2ed5b3bf1131.png">
我这也跑不起来

[✓] Flutter (Channel beta, v1.6.3, on Mac OS X 10.14.5 18F132, locale zh-Hans-CN)
    • Flutter version 1.6.3 at /Users/nnianhou/flutter
    • Framework revision bc7bc94083 (4 weeks ago), 2019-05-23 10:29:07 -0700
    • Engine revision 8dc3a4cde2
    • Dart version 2.3.2 (build 2.3.2-dev.0.0 e3edfd36b2)

**Comment by Sky24n** [comment]
这不是我的项目吧？！
