### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by l114624915** [Sky24n/flutter_wanandroid#65]
Compiler message:
file:///Users/xxx/Documents/flutter/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6/lib/src/widget_util.dart:88:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^

**Comment by CacuBY** [comment]
这个解决了么

**Comment by zhenxiaobin** [comment]
同样的问题，等大神解决

**Comment by Sky24n** [comment]
本项目基于Flutter (Channel beta, v1.6.3, locale zh-Hans-CN)开发！
请自行升级Flutter版本！
flutter upgrade
