### ISSUE TITLE
v0.2.1版本开源详情

### ISSUE THREAD

**Issue by Sky24n** [Sky24n/flutter_wanandroid#66]
一、Flutter常用工具类库全面升级 [flustars](https://github.com/Sky24n/flustars)
1. SpUtil 全面支持读取对象，对象列表。无需通过SpHelper二次转换。
```dart
City hisCity = SpUtil.getObj("loc_city", (v) => City.fromJson(v));  
List<City> dataList = SpUtil.getObjList("loc_city_list", (v) => City.fromJson(v));
```
2. ScreenUtil 兼容横/纵屏适配。
```dart
double adapterSize = ScreenUtil.getInstance().getAdapterSize(100);
double adapterSize = ScreenUtil.getAdapterSizeCtx(context, 100)
```
3. DirectoryUtil 新增文件目录工具类。  
```dart
await DirectoryUtil.getInstance();
String path = DirectoryUtil.getTempPath(fileName: 'demo.png', category: 'image');
String path = DirectoryUtil.getAppDocPath(fileName: 'demo.mp4', category: 'video');
String path = DirectoryUtil.getStoragePath(fileName: 'flutterwanandroid.apk', package: 'com.thl.flutterwanandroid');

Directory dir = DirectoryUtil.createTempDirSync(package: 'doc', category: 'image');
```  
二、Flutter全局屏幕适配库 [auto_size](https://github.com/flutterchina/auto_size) 
```  dart
import 'package:auto_size/auto_size.dart';

/// 默认设计稿尺寸360*640，单位dp。
void main() => runAutoSizeApp(MyApp());

void main() => runAutoSizeApp(MyApp(), width: designWidth, height: designeight);
```  
三、基础组件库[base_library](https://github.com/Sky24n/FlutterRepos)，方便多个项目共用。
包含：Dart 常用工具类库 common_utils，Flutter 常用工具类库 flustars，网络 dio，国际化 fluintl，屏幕适配 auto_size。
另外附送[login_demo](https://github.com/Sky24n/FlutterRepos/tree/master/login_demo)示例！关于App启动时，未登录跳登录页，已登录进主页。

四、关于本库相关   
1.登录/注册     （已开源）
2.收藏功能      （整理中） 
3.网络状态页   （整理中）
项目正在整理开源中！如无法运行，请自行回滚到该节点。
```dart
git reset --hard 777f6e7fc221b30abf480c94d686c955fe661b0e
```

**Comment by Hiram-Y** [comment]
你好 在打开webview的时候 会出现loading，这段代码我怎么没找到呢

**Comment by kovlento** [comment]
你好，请问一下版本更新功能怎么做吗？有没有文章介绍？
