### ISSUE TITLE
报了一大堆的错误怎么处理

### ISSUE THREAD

**Issue by slhaos** [Sky24n/flutter_wanandroid#75]
Compiler message:
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:88:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:88:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(
                                            ^
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:121:26: Error: Method not found: 'ImageStreamListener'.
        .addListener(new ImageStreamListener(
                         ^^^^^^^^^^^^^^^^^^^
file:///Users/wodediannao/flutter/.pub-cache/hosted/pub.flutter-io.cn/flustars-0.2.6+1/lib/src/widget_util.dart:121:45: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
        .addListener(new ImageStreamListener(
                                            ^
Compiler failed on /Users/wodediannao/flutter_wanandroid-master/lib/main.dart
Finished with error: Gradle task assembleDebug failed with exit code 1

**Comment by ShellPeng** [comment]
你的flutter版本低了
