### ISSUE TITLE
auto_size无法添加

### ISSUE THREAD

**Issue by IPOSDai** [Sky24n/flutter_wanandroid#78]
Running "flutter packages get" in flutter_wanandroid-master...                                   Could not find a file named "pubspec.yaml" in git://github.com/flutterchina/auto_size.git b593f5167bce84fb3cad5c258477bf3abc1b14eb.

**Comment by Sky24n** [comment]
更新最新代码！
如果不行，修改 url: https://github.com/flutterchina/auto_size.git
如果还是不行，就clone到本地引用，或者把这个库屏蔽了不使用
