### ISSUE TITLE
在体系的下 上拉加载分页bug

### ISSUE THREAD

**Issue by hzp1993** [Sky24n/flutter_wanandroid#79]
在体系的下 找到开源项目进去 上拉加载page 3 然后点击一个文章进入详情页页面再返回来 然后再上拉加载数据 会变成page 2的数据，每次进入详情页 再返回 _comListPage 都会被重置 怎么让它不被重置

**Comment by Sky24n** [comment]
还没有找到好的解决方案


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
