### ISSUE TITLE
页面抖动厉害

### ISSUE THREAD

**Issue by wuyugege** [Sky24n/flutter_wanandroid#80]
不知道大家有没有发现，从APP切到其他APP再切回来，刚开始滑动的时候，页面抖动的厉害。

我用iPhone xs发现了这个问题，安卓没发现。

**Comment by Sky24n** [comment]
没有在真机运行过，你可以试下其他线上APP是否存在该问题，例如flutter go，如果都存在说明是flutter的问题


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)
