### ISSUE TITLE
关于dio_util.dart 文件使用。

### ISSUE THREAD

**Issue by uddsoft** [Sky24n/flutter_wanandroid#82]
我的接口请求返回的数据格式：
`{"code":1,"data":{"token":"67a84c282f991fa46e10bbd1e28efd4b","token_time":1567047434}}`

使用dio_util请求代码如下：
 BaseResp<Map<String,dynamic>> baseResp = await DioUtil().request(Method.post, ApiUrl.url_passport_login,data: data);
    print(baseResp);
结果：
只能拿到接口返回的data部分数据。想要完整拿到数据，这种情况需要改接口数据返回格式吗。

**Comment by uddsoft** [comment]
我看到您 DioUtil().requestR 方法 返回的 BaseRespR 里面带了一个response 属性。我使用了这个。

**Comment by Sky24n** [comment]
BaseResp 里面有基础字段code，data，msg啊！用DioUtil().request就可以了啊

**Comment by uddsoft** [comment]
好的。
