### ISSUE TITLE
关于dio headers. 为什么我的没有set-cookie 这个name。

### ISSUE THREAD

**Issue by uddsoft** [Sky24n/flutter_wanandroid#83]
关于dio headers. 为什么我的没有set-cookie 这个name。
  baseRespR.response.headers.forEach((String name,List<String> values) {
      print(name);
      if(name == "set-cookie") {
        String cookie = values.toString();
        LogUtil.e("set-cookie:" + cookie);
        SpUtil.putString(BaseConstant.keyAppToken, cookie);
        DioUtil().setCookie(cookie);
      }
    });

**Comment by Sky24n** [comment]
跟你们服务端接口有关，有可能接口并未返回
