### ISSUE TITLE
flukit依赖引入失败

### ISSUE THREAD

**Issue by kandroid29** [Sky24n/flutter_wanandroid#9]
pubspec.yaml里有一个flukit的依赖
flukit:
    git:
      url: git://github.com/flutterchina/flukit.git
      path: package_src

在命令行运行flutter packages get后，提示一下错误信息：

Git error. Command: git clone --mirror git://github.com/flutterchina/flukit.git D:\DevTools\flutter-v1.0\.pub-cache\git\cache\flukit-2a67abdff339ccbeb94f2bceded09b33a4657e54
Cloning into bare repository 'D:\DevTools\flutter-v1.0\.pub-cache\git\cache\flukit-2a67abdff339ccbeb94f2bceded09b33a4657e54'...
fatal: unable to look up github.com (port 9418) (应用程序没有调用 WSAStartup，或者 WSAStartup 失败。 )
pub get failed (69) -- attempting retry 1 in 1 second...
Could not find a file named "package_src/pubspec.yaml" in git://github.com/flutterchina/flukit.git 5391447fae6209bb21a89e6a5a6583cac1af9b4b.
pub get failed (1)

能看下是什么原因吗？

**Comment by Sky24n** [comment]
你把这个目录下面的flukit相关的删除了，重新flutter packages get
D:\DevTools\flutter-v1.0.pub-cache\git\cache\

**Comment by kandroid29** [comment]
问题已解决，把
url: git://github.com/flutterchina/flukit.git
改为
url: https://github.com/flutterchina/flukit.git

可能是flutter依赖不支持git协议?

**Comment by Sky24n** [comment]
应该是git版本的问题，我的版本是2.18.0
