### ISSUE TITLE
我想请教下，是用rxdart后，CPU和内存一直高占用率是正常情况么？

### ISSUE THREAD

**Issue by beydeng** [Sky24n/flutter_wanandroid#90]
我看了好几个关于rxdart的项目结构，发现cpu使用率普遍在30%+上，而且是在页面已经加载完成的情况下，这30%会一直使用，按理说页面加载完成，cpu应该是0%的使用率；而且内存基本会到200M，有时会上200+。
这是什么原因导致的

**Comment by Sky24n** [comment]
我猜测有可能是状态保持AutomaticKeepAliveClientMixin引起的

**Comment by Sky24n** [comment]
你可以新建一个项目，只用rxdart看看cpu使用情况

**Comment by beydeng** [comment]
我也试过了，发现情况都类似

**Comment by Sky24n** [comment]
rxdart引起的？

**Comment by beydeng** [comment]
嗯 ，只能是这个了... 我也很好奇，晚上基本找不到关于内存和CPU占用情况的帖子...
我只要不使用rxdart，内存基本就100多，CPU页面加载完成之后就回复到0%，看起来还算正常....
