### ISSUE TITLE
代码跑不起来 如下

### ISSUE THREAD

**Issue by GuixiangCao** [Sky24n/flutter_wanandroid#94]
Compiler message:
../../../../../../.pub-cache/hosted/pub.flutter-io.cn/cached_network_image-1.1.3/lib/src/cached_network_image_provider.dart:42:24: Error: The method 'CachedNetworkImageProvider.load' has fewer positional arguments than those of overridden method 'ImageProvider.load'.
  ImageStreamCompleter load(CachedNetworkImageProvider key) {
                       ^
../../../../../../flutter/packages/flutter/lib/src/painting/image_provider.dart:403:24: Context: This is the overridden method ('load').
  ImageStreamCompleter load(T key, DecoderCallback decode);
                       ^
Target kernel_snapshot failed: Exception: Errors during snapshot creation: null
Failed to build bundle.

**Comment by Sky24n** [comment]
flutter 版本呢

**Comment by mazhengim** [comment]
将cached_network_image的版本号升级到2.0.0-rc即可解决
cached_network_image: ^2.0.0-rc

**Comment by zh1992** [comment]
今天刚试，使用作者的版本可以, 使用另一个版本失败；

success:  Flutter (Channel beta, v1.10.7, locale zh-Hans-CN)
failure: Flutter (Channel beta, v1.11, locale zh-Hans-CN)

**Comment by addappcn** [comment]
我也一样用的最新版本报这个错  ，这flutter sdk 不一样竟然运行不了 兼容下太差

**Comment by addappcn** [comment]
将cached_network_image的版本号升级到2.0.0即可解决
cached_network_image: ^2.0.0

**Comment by SuperZiLu** [comment]
我从github拉下项目 遇到同样的问题 通过升级cached_network_image插件的版本号到2.0.0解决
