### ISSUE TITLE
请问启动页和splash页面之间的黑屏怎么处理的

### ISSUE THREAD

**Issue by YQYOnTheRoad** [Sky24n/flutter_wanandroid#99]
我写的Demo打开到启动页的时候点击隐藏虚拟导航栏就会闪黑屏后进入splash页面。而从你的代码运行起来的不会是什么原因呢。（页面代码是和你的一样的） 正常打开的话不会闪黑屏  

百度后已经设置了android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"还是无效。

**Comment by YQYOnTheRoad** [comment]
<meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />

**Comment by androidDL** [comment]
作者的是老版本的flutter，与新的flutter使用的MainActivity引用的FlutterActivity不一样。老版本就像作者这个app一样，启动屏、闪屏再到flutter页面，图片不会伸缩。新版本的话，得将AndroidManifest中的
`<meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />`（如果有的话)
改成
`<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />`
当然launch_background还是得按作者的写，要不然图片不能伸缩到除了顶上和底下导航栏的全部空间。

**Comment by YQYOnTheRoad** [comment]
> 作者的是老版本的flutter，与新的flutter使用的MainActivity引用的FlutterActivity不一样。老版本就像作者这个app一样，启动屏、闪屏再到flutter页面，图片不会伸缩。新版本的话，得将AndroidManifest中的
> `<meta-data android:name="io.flutter.app.android.SplashScreenUntilFirstFrame" android:value="true" />`（如果有的话)
> 改成
> `<meta-data android:name="io.flutter.embedding.android.SplashScreenDrawable" android:resource="@drawable/launch_background" />`
> 当然launch_background还是得按作者的写，要不然图片不能伸缩到除了顶上和底下导航栏的全部空间。

当时已经找到答案 忘记来关了 还是很谢谢你的回答！

**Comment by androidDL** [comment]
@YQYOnTheRoad 你的解决方式是什么呢？

**Comment by YQYOnTheRoad** [comment]
> @YQYOnTheRoad 你的解决方式是什么呢？

就是你上面提到的那个方式。
我这里遇到一个新的问题。我在dio拦截器中添加header去验证token，token失效需要跳转到登陆界面，dio中没有context，怎么才能跳转到登陆界面呢，我目前想到2个方式但感觉都不是很方便。
1 每个请求中添加参数BuildContext 
2 全局缓存一个当前页面的BuildContext （每次跳转路由更新一次）
请问有什么更加合理的方式去解决吗
